disabled_rules: # rule identifiers to exclude from running
  - colon
  - comma
  - control_statement
  - line_length
  - force_cast
  - force_try
opt_in_rules: # some rules are only opt-in
  - empty_count

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods


